print("Vamos calcular a sua nota do enem!")
print("Insira sua nota de Linguagens,Humanas,Matemática,Ciências da Natureza e por último redação")
ling = float (input("Linguagens") )
hum = float(input("Humanas") )
mat = float(input("Matemática") )
cie = float(input("Ciências da Natureza"))
red = float(input("Redação"))
nota = float((2*ling + 2*cie + 2*red + 3*mat + hum)/10)
print("Parabéns,sua nota é,",nota)
